module.exports = {
  mode: "jit",
  purge: {
    content: [
      "./*/*.php",
      "./**/*.php",
      "./resources/css/*.css",
      "./resources/js/*.js",
      "../../plugins/ai-hub-blocks/src/**/*.js",
      "./node_modules/tw-elements/dist/js/**/*.js",
    ],
    safelist: [
      "absolute",
      "relative",
      "md:top-28",
      "pb-60",
      "md:pb-0",
      "top-72",
      "md:w-2/4",
      "w-auto",
      "z-10",
      "mb-10",
      "font-bold",
      "flex-wrap",
      "justify-end",
      "lg:flex-row",
      "flex-col",
      "md:justify-center",
      "max-w-md",
      "mb-12",
      "mt-6",
      "lg:mr-44",
      "lg:pb-[80px]",
      "pb-0",
      "pb-[80px]",
      "lg:pb-0",
      "lg:mt-4",
      "justify-center",
      "lg:justify-start",
      "xl:mt-10",
      "mt-0",
      "mt-10",
      "hidden",
      "md:block",
      "block",
      "order-2",
      "lg:order-1",
      "order-1",
      "lg:order-1",
      "order-2",
      "md:hidden",
      "flex",
      "md:flex",
      "md:pr-0",
      "md:items-center",
      "justify-center",
      "md:justify-start",
      "md:flex-row",
      "mb-6",
      "md:mb-0",
      "content-padding-left",
      "content-padding-right",
      "mt-20",
      "h-[430px]",
      "capitalize",
      "text-2xl",
      "pl",
      "min-w-[300px]",
      "w",
      "min-w-[370px]",
      "font-light",
      "max-w-[1200px]",
      "min-w-[687px]",
      "mt",
      "my",
      "py",
      "border",
      "font",
      "text",
      "mb",
      "ml",
      "ml-[25px]",
      "bg",
      "px",
      "px-[20px]",
      "ellipsis",
      "overflow",
      "hidden",
      "mr",
      "my-24"
    ],
  },
  theme: {
    extend: {
      colors: {
        primary: "#86BC25",
        dark: "#1C1C1C",
      },
      fontFamily: {
        roboto: "Roboto",
        sans: "Open Sans",
      },
      textColor: {
        primary: "#86BC25",
      },
      container: {
        padding: {
          DEFAULT: "1rem",
          sm: "2rem",
          lg: "0rem",
        },
      },
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1440px",
      },
      fontSize: {
        title: ["40px", "54px"],
        "small-text": ["12px", "20px"],
      },
      backgroundImage: {
        search: "url('/wp-content/uploads/2021/12/Shape.png')",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("tw-elements/dist/plugin")],
};
